services:
    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile
        env_file:
            - ./backend/.env
        ports:
            - "8000:8000"
    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        env_file:
            - ./frontend/.env.local
        environment:
            - NEXT_PUBLIC_API_URL=http://backend:8000
        ports:
            - "3000:3000"
        depends_on:
            - backend
